name: or_training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - nb_conda_kernels
  - jupyter
  - notebook
  - ipykernel
  - numpy
  - scipy
  - pytest
  - pip
  - pip:
    - cylp
